// models/Url.js
import mongoose from "mongoose";
import { nanoid } from "nanoid"; // Nanoid is used to generate a unique shortId

const urlSchema = new mongoose.Schema({
  originalUrl: { type: String, required: true }, // Field to store the original URL
  shortId: { type: String, required: true, default: () => nanoid(8) }, // Unique shortId generated by nanoid
  createdAt: { type: Date, default: Date.now }, // Timestamp for URL creation
});

const Url = mongoose.models.Url || mongoose.model("Url", urlSchema);

export default Url;
